language: node_js
node_js:
- lts/*
script:
- yarn build
deploy:
- provider: script
  skip_cleanup: true
  script:
  - npx @dhis2/cli-utils release --publish npm
  on:
    tags: false
    branch: master
env:
  global:
  - GIT_AUTHOR_NAME=@dhis2-bot
  - GIT_AUTHOR_EMAIL=apps@dhis2.org
  - GIT_COMMITTER_NAME=@dhis2-bot
  - GIT_COMMITTER_EMAIL=apps@dhis2.org
  - secure: QJnQGfVgfikp12vF4Hk1ZHnXYy68kLhOdPgzDvQfqXhCsbQglKQLut6/k48yvGTi1X2wtW8cwFsRM8+p0VM/aZilX5tpd1a0JGUsZjLv2sDQJVdYBe7PllM3fq0BX9yXBWpxUkBFQzPnTKLEGFWQcx3pvhEOInFP0iBxnNJ6d60Wqkk5x9OxvufgjeCFKQKH3ityQGMkI+vF6ykllJMCetN61JVw+oP4msy7pGfxU6dvNrZrfJ7oOvn6HuObCR2yNlwKW+xsNOH62gEkbi158yO3RUiW+RHT8kFjY3Gpg9FtjqnxRfe2sUDN0jgu5/HeKsW7A+bntFIMm6+CrsvqMMqkXOX+FLhbeIzxTeHf+gIP1maVeYlXIkiBpUCLSjsyNxMcWbXJCnCseIsyzTeVuw1RRuo4RNKWQ+myIRJtAgS8O5ge0Pewo3aXB7InOq1dSxoWrnHY3LgecCKJ/nhPAmBddwLtBa9JQR2Kr0mtFunTAVwCDF7fY0yFXvtSJyrMVT0yXd0s75Q1n6uf9sXcq/F+sPwtrrbQObuA543qqh7otqOH1FK/K9LnDs/RWChArxCdoU/C9UEoUqfV9luu+940mdBG0BXipIRPhrj0dOIC5+Uj+I4LT9xMuykr/b3CGWI4e4eSE0qL5sUZexQtR/VMVsRMn2pvM39J5/0gny0=
  - secure: OJuijGttE11oHgL81pW2v7RvEh29J4o92jpJYsn/bIO+ZXMBPrrRIFTxU+8amsEeLi0yLqaM2AttuRCjgepkyIlA6na4j0M+gM1eILhyP+ABWX0t0ccNIysXDIwQWvYUym3WGgK1HbziSHW11oHCqXODqC9lLgIQDh8wH0qOUmKdecLEs7RrgqYSzwYxwZJ53Kaux8VH8GYpKpbNABUZ1UaB4P8qRNICV5Vvpkr7QCISTlNJwyHoSXWSkkQ9Y/JqDJMCXm64MihfM0flM4P1nTc4i1KwYUGDr6c+0oTFLqe/pH2Dn9jzddTq6gvCUrRgWSV3eZCEcfIDdwX/dF7uV9p4pL0y+VfCqWpH9b5OuQ4CgzeR8fjgqGg8A7h6PPpXFIGCJWsYsRAyWHGaXAEL2ryzc67ab4lzntKwUrMGFMoVHKKlLe8zfpJ3qdBFjjOrS/tUNAkC0jAVcEFyCcXQZdQCyUyp1YbwX4vf11il6tcZqFMeRNrGSXzrKCaL0tlOsWLz1xjmh4EPbTbXbTpuc1/yE/xBPI9mbs8jb6o1L6cbUVhuNviurZ7AxuGgcNkIodAX/eq2ztQK8oI8xy/1qBbeh1MkqkBr0wIerNJCnPz1OVBI4SHWAhGhKeTRbL8qJFGgqlEeD6tqGYeUUW95bza55bDVF06Zl6TrvYF2iqs=
