[build]
  command = "yarn install --frozen-lockfile && yarn build"
  publish = "build/docs/"

[[redirects]]
  from = "/demo/*"
  to = "https://ui.dhis2.nu/demo"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "https://ui.dhis2.nu"
  status = 301
  force = true
