name: 'DHIS2: Style'

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    pr:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: Install
              run: yarn install

            - name: Run linters
              run: yarn lint
        env:
            CI: true
