name: 'DHIS2'

on: [push]

jobs:
    pr:
        name: Style
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: Install
              run: yarn install

            - name: Lint
              run: yarn lint
        env:
            CI: true
